# Generated by Django 5.0.6 on 2024-05-31 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_list', '0002_remove_watchlist_platform_delete_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 12, 4, 30, 701506)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 12, 4, 30, 701506)),
        ),
    ]
