# Generated by Django 5.0.6 on 2024-05-31 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_list', '0003_alter_watchlist_created_alter_watchlist_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 12, 18, 37, 381089)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
