# Generated by Django 5.0.6 on 2024-05-31 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_list', '0004_alter_watchlist_created_alter_watchlist_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('website', models.URLField()),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 5, 31, 12, 35, 0, 309672))),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 12, 35, 0, 294053)),
        ),
    ]
