# Generated by Django 5.0.6 on 2024-05-31 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_list', '0005_streamplatform_alter_watchlist_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 14, 12, 7, 152260)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 14, 12, 7, 152260)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 14, 12, 7, 152260)),
        ),
    ]
