# Generated by Django 5.0.6 on 2024-05-31 12:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_list', '0006_alter_streamplatform_created_alter_watchlist_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 5, 31, 17, 35, 50, 340510))),
                ('updated', models.DateTimeField(default=datetime.datetime(2024, 5, 31, 17, 35, 50, 340510))),
            ],
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 17, 35, 50, 340510)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 17, 35, 50, 340510)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 17, 35, 50, 340510)),
        ),
    ]
